site_name: ARCHIVE

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  font: false
  
plugins:
  - search
  - awesome-pages

markdown_extensions:
  - nl2br

extra_css:
  - stylesheets/extra.css
