site_name: ARCHIVE
site_url: https://4sighttt.github.io/ARCHIVE/

theme:
  name: material
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  font: false

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: night

    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: sunny

copyright: Copyright © 2026 4sighttt. All rights reserved.
  
plugins:
  - search
  - awesome-pages

markdown_extensions:
  - nl2br
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

/* TOC 현재 위치 강조 */
.md-nav__link--active {
  color: #ffcc66 !important;   /* 강조 색 */
  font-weight: 700;
}

/* 활성 항목 왼쪽 바 추가 (추천) */
.md-nav__link--active::before {
  content: "";
  display: inline-block;
  width: 4px;
  height: 1em;
  background: #ffcc66;
  margin-right: 6px;
  vertical-align: middle;
}
